FROM postgres

ENV POSTGRES_USER docker
ENV POSTGRES_PASSWORD post123

COPY demokratis_db_docker_fakedata.sql /docker-entrypoint-initdb.d/demokratis_db_docker_fakedata.sql
 #will be executed automatically

